### ISSUE TITLE
Load archived world files from a URL

### ISSUE THREAD

**Issue by markrcote** [benwebber/ansible-minecraft#6]
It would be nice if ansible-minecraft could load world files from an archive, either local or remote. This would only happen if there was no world present (generally, a new installation). We could autodetect standard archive types (zip, tarball).

I'm planning on working on this if you think it makes sense (comments welcome on general requirements/design).

**Comment by benwebber** [comment]
This is a cool idea. As an intermediate step, what about a sort of hook/stage system?

We might write:

``` yaml
- hosts: all
  roles:
    role: benwebber.minecraft
    minecraft_before_server_start: "{{ playbook_dir }}/download-world.yml"
```

[Ansistrano](https://github.com/ansistrano/deploy/) uses this technique to great effect.

**Comment by benwebber** [comment]
I have released 3.0.0 with support for `server.properties` and hooks. Will the before start hook work for your use case?

**Comment by markrcote** [comment]
Yeah, that would work. Looks pretty straightforward.

**Comment by benwebber** [comment]
Great! Let me know if you run into any issues.

I'm not opposed to rolling this feature into the role, but it would need to be sufficiently generic enough to help most users.

Down the line, we could ship includes with the role itself. Users could use them like so:

``` yaml
- hosts: all
  roles:
    role: benwebber.minecraft
    minecraft_hook_before_start: "{{ role_path }}/tasks/hooks/before-start/download-world.yml"
```
